### ISSUE TITLE
[ROS2] Add back in pcl methods in grid_map_sdf once pcl_ros is available in ROS2

### ISSUE THREAD

**Issue by SteveMacenski** [ANYbotics/grid_map#243]
currently pcl_ros is not available in ROS2 so the imported headers and conversion functions in grid_map_sdf cannot be fully ported at this time, but all the rest of it is.

Once pcl_ros is ported to ROS2, we can enable this.

**Comment by maximilianwulf** [comment]
Is the ROS2 navigation group going to do it? 
Maybe we have to check if the package can work independent of `pcl_ros`.

**Comment by maximilianwulf** [comment]
Related to #241 .

**Comment by SteveMacenski** [comment]
I'm not sure off hand, one project at a time, pcl_ros isn't a small package. I also am a maintainer on that as well so I can help with getting things pushed through but we simply haven't discussed this in the context of the navigation working group

**Comment by maximilianwulf** [comment]
Okay, thanks. I will check if we can have this package independent of `pcl_ros`.

**Comment by Marwan99** [comment]
`pcl_ros` is now available in case you decide to continue using it.

I think this also needs to be added to the list in #283.

**Comment by SteveMacenski** [comment]
pcl ros for ROS 2 is still not available - we haven't ported it yet

**Comment by mitsudome-r** [comment]
@SteveMacenski 
Hi, I'm using this package for my project, and it also helps us if this is released as binary since it will reduce our build time. I was looking to see if there is anything I can help, and I've noticed that there could be alternative solution instead of waiting pcl_ros to be released. Could you take a look at https://github.com/ANYbotics/grid_map/pull/299, and see if the solution works for you?

**Comment by SteveMacenski** [comment]
That works for me! Closing ticket since PR resolves
